trigger:
  branches:
    include: 
      - master
  paths:
    exclude:
      - README.md

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python3:
      python.version: '3.12'
      architecture: 'x64'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use python $(python.version)'

- script: |
    pip install --upgrade sphinx
  displayName: 'Install sphinx'

- script: |
    pip install --upgrade sphinx_rtd_theme
  displayName: 'Install sphinx_rtd_theme'

- task: CmdLine@2
  inputs:
    script: 'make html' 
    workingDirectory: '$(build.sourcesdirectory)' 
  displayName: 'Compile documentation'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)/_build/html'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish documentation as artifact'